In [1]:
# from google.colab import drive
# drive.mount('/content/drive')
# drive.mount('/content/drive', force_remount=True)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'matplotlib'

In [3]:
cigs = pd.read_csv('cigs.csv')
cigs.head()

Brand_Name flavor  CO  nic   tar  size filter pack menthol
0    Alpine     NaN  15  1.1  16.0   100      F   SP     yes
1    Alpine      Lt  12  0.8  10.0   100      F   SP     yes
2    Alpine     NaN  15  1.1  16.0  King      F   HP     yes
3    Alpine      Lt  11  0.7  10.0  King      F   HP     yes
4    Alpine     NaN  16  1.0  16.0  King      F   SP     yes

In [4]:
cigs.shape

(1125, 9)

In [5]:
cigs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Brand_Name  1125 non-null   object 
 1   flavor      907 non-null    object 
 2   CO          1125 non-null   int64  
 3   nic         1125 non-null   float64
 4   tar         1125 non-null   float64
 5   size        1125 non-null   object 
 6   filter      1125 non-null   object 
 7   pack        1125 non-null   object 
 8   menthol     1125 non-null   object 
dtypes: float64(2), int64(1), object(6)
memory usage: 79.2+ KB


In [6]:
X = cigs['CO'].values
y = cigs['tar'].values

In [7]:
# look a X data
X

array([15, 12, 15, ..., 12,  6, 16])

In [8]:
# look at y data
y

array([16., 10., 16., ...,  9.,  4., 20.])

In [9]:
# reshape data and create 2 dimen array for train-test data
X = X.reshape(-1,1)
X

array([[15],
       [12],
       [15],
       ...,
       [12],
       [ 6],
       [16]])

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=.8, test_size=.2, random_state=100)

NameError: name 'train_test_split' is not defined

In [11]:
# print out some data
print(f'X_Train shape [{x_train.shape}]')
print(f'X_Test shape [{x_test.shape}]')
print(f'y_Train shape [{y_train.shape}]')
print(f'y_Test shape [{y_test.shape}]')

NameError: name 'x_train' is not defined

In [12]:
# make scatter plot and labels
plt.scatter(x_train, y_train, color='red')
plt.xlabel('CO (mg of CO, rounded to nearest mg')
plt.ylabel('Tar (mg of tar, rounded to nearest mg')
plt.title('Amount of Tar vs Carbon Monoxide output')
plt.show()

NameError: name 'plt' is not defined

In [13]:
# create liner reg model
lm = LinearRegression()
lm.fit(x_train, y_train)

NameError: name 'LinearRegression' is not defined

In [14]:
# print accuracy rate
print(f'Train Accuracy {round(lm.score(x_train, y_train)*100,2)}%')
print(f'Test Accuracy {round(lm.score(x_train, y_train)*100,2)}%')

NameError: name 'lm' is not defined

In [15]:
# create plot with prediction model line
plt.scatter(x_train, y_train, color='red')
plt.plot(x_test, y_predict)
plt.xlabel('CO (mg of CO, rounded to nearest mg')
plt.ylabel('Tar (mg of tar, rounded to nearest mg')
plt.title('Amount of Tar vs Carbon Monoxide output')
plt.plot

NameError: name 'plt' is not defined

## Conclusions
1. While cigarettes that have more tar are more likely to have more carbon monoxide output, accuracy prediction is only at 67%. 
2. Discrepancies appear to widen when the tar amount is over 15 mg.
3. The cigarette with the highest tar amount (~20mg) is not directly correlated with the cigarette with the highest CO emmission (~22 mg). 